<?php

/**
 * @file
 * Install, update, & uninstall functions for Email Change Confirmation module.
 */

/**
 * Implements hook_update_last_removed().
 */
function email_confirm_update_last_removed() {
  return 7000;
}

/**
 * Move email_confirm settings from variables to config.
 */
function email_confirm_update_1000() {
  // Migrate variables to config.
  $config = config('email_confirm.settings');
  $config->set('email_confirm_confirmation_email_subject', update_variable_get('email_confirm_confirmation_email_subject', ''));
  $config->set('email_confirm_confirmation_email_author', update_variable_get('email_confirm_confirmation_email_author', ''));
  $config->set('email_confirm_confirmation_email_bcc', update_variable_get('email_confirm_confirmation_email_bcc', ''));
  $config->set('email_confirm_confirmation_email_body', update_variable_get('email_confirm_confirmation_email_body', ''));
  $config->set('email_confirm_confirmation_original_email_body', update_variable_get('email_confirm_confirmation_original_email_body', ''));
  $config->set('email_confirm_hash_salt', update_variable_get('email_confirm_hash_salt', ''));
  $config->set('email_confirm_timeout', update_variable_get('email_confirm_timeout', ''));
  $config->save();

  update_variable_del('email_confirm_confirmation_email_subject');
  update_variable_del('email_confirm_confirmation_email_author');
  update_variable_del('email_confirm_confirmation_email_bcc');
  update_variable_del('email_confirm_confirmation_email_body');
  update_variable_del('email_confirm_confirmation_original_email_body');
  update_variable_del('email_confirm_hash_salt');
  update_variable_del('email_confirm_timeout');
}
