<?php

/**
 * @file
 * Install, update and uninstall functions for the Email Chhange Confirmation module.
 */

/**
 * Implement hook_uninstall().
 */
function email_confirm_uninstall() {
  variable_del('email_confirm_confirmation_email_subject');
  variable_del('email_confirm_confirmation_email_author');
  variable_del('email_confirm_confirmation_email_bcc');
  variable_del('email_confirm_confirmation_email_body');
  variable_del('email_confirm_confirmation_original_email_body');
}
